apiVersion: batch/v1
kind: Job
metadata:
  creationTimestamp: null
  name: nginx
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
      restartPolicy: Never
status: {}
