services:
  drupal:
    image: custom-drupal:latest
    ports:
    - mode: ingress
      target: 80
      published: 80
      protocol: tcp
    volumes:
    - type: volume
      source: drupal-modules
      target: /var/www/html/modules
      volume: {}
    - type: volume
      source: drupal-profiles
      target: /var/www/html/profiles
      volume: {}
    - type: volume
      source: drupal-sites
      target: /var/www/html/sites
      volume: {}
    - type: volume
      source: drupal-themes
      target: /var/www/html/themes
      volume: {}
  postgres:
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/psql-pw
    image: postgres:12.1
    secrets:
    - source: psql-pw
    volumes:
    - type: volume
      source: drupal-data
      target: /var/lib/postgresql/data
      volume: {}
volumes:
  drupal-data: {}
  drupal-modules: {}
  drupal-profiles: {}
  drupal-sites: {}
  drupal-themes: {}
secrets:
  psql-pw:
    name: psql-pw
    external: true
